name: firestore_paging_controller
description: "Lazily load and display pages of items as the user scrolls down your screen, using Firestore with some enhancements."
version: 0.1.0
homepage: https://github.com/StageCoding/firestore_paging_controller

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  infinite_scroll_pagination: ^4.1.0
  cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.5
  test: ^1.25.8
  build_runner: ^2.4.14

  cloud_firestore_platform_interface: ^6.6.0
  firebase_core: ^3.9.0
